name: Feature Request
description: File a request for a feature or idea
title: "[Feature]: "
lable: "feature request"
projects: "food-hound-project"
body:
- type: markdown
  attributes:
    value: Acceptance Criteria
- type: input
  attributes:
    label: "When I ..."
    placeholder: "Open view the home page"
  validations:
    required: true
- type: input
  attributes:
    label: "Then ..."
    placeholder: "I see a section for navigation, a description of the site, the logo, and a sign up button"
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      - [ ] nav section
      - [ ]
  validations:
    required: false
        
